"""Seed the database with sample job listings."""
import sys
sys.path.insert(0, ".")
from app.core.database import SessionLocal, create_tables
from app.models.models import Job
from datetime import datetime, timedelta
import random

SAMPLE_JOBS = [
    {"title": "Senior Python Developer", "company": "TechCorp Inc.", "location": "San Francisco, CA", "description": "We are looking for a Senior Python Developer. Requirements: 5+ years of experience with Python, Django or FastAPI, PostgreSQL, Redis, Docker, Kubernetes, CI/CD pipelines, REST API design, microservices architecture. Responsibilities: Design scalable backend services, write clean code, mentor junior developers.", "skills_required": ["python", "django", "fastapi", "postgresql", "redis", "docker", "kubernetes", "rest api", "microservices"], "experience_min": 5.0, "experience_max": 8.0, "salary_min": 140000, "salary_max": 180000, "job_type": "full-time", "remote": True, "category": "Backend Development"},
    {"title": "Frontend React Developer", "company": "WebFlow Studios", "location": "New York, NY", "description": "Join our team as a Frontend React Developer. Requirements: 3+ years with React.js, TypeScript, Next.js, Tailwind CSS, state management, REST APIs and GraphQL, responsive design. Build performant UIs from Figma mockups.", "skills_required": ["react", "typescript", "next.js", "tailwind", "css", "html", "javascript", "graphql", "git"], "experience_min": 3.0, "experience_max": 6.0, "salary_min": 110000, "salary_max": 150000, "job_type": "full-time", "remote": False, "category": "Frontend Development"},
    {"title": "Machine Learning Engineer", "company": "AI Solutions Ltd.", "location": "Seattle, WA", "description": "Hiring ML Engineer to build next-gen AI systems. Requirements: 4+ years ML/AI experience, Python, TensorFlow or PyTorch, NLP and Computer Vision, scikit-learn, pandas, deep learning, AWS SageMaker. Deploy ML models to production.", "skills_required": ["python", "machine learning", "tensorflow", "pytorch", "nlp", "scikit-learn", "pandas", "numpy", "deep learning", "aws"], "experience_min": 4.0, "experience_max": 7.0, "salary_min": 150000, "salary_max": 200000, "job_type": "full-time", "remote": True, "category": "Machine Learning"},
    {"title": "Full Stack Developer", "company": "StartupXYZ", "location": "Austin, TX", "description": "Full Stack Developer for SaaS platform. Requirements: 3+ years full-stack, JavaScript/TypeScript, React, Node.js, PostgreSQL, MongoDB, AWS or GCP, agile methodologies.", "skills_required": ["javascript", "typescript", "react", "node.js", "postgresql", "mongodb", "aws", "git", "agile"], "experience_min": 3.0, "experience_max": 6.0, "salary_min": 120000, "salary_max": 160000, "job_type": "full-time", "remote": True, "category": "Full Stack"},
    {"title": "Data Scientist", "company": "DataDriven Analytics", "location": "Chicago, IL", "description": "Data Scientist to derive insights from complex datasets. Requirements: 3+ years data science, Python, R, pandas, NumPy, scikit-learn, SQL, machine learning algorithms, Tableau or Power BI.", "skills_required": ["python", "r", "pandas", "numpy", "scikit-learn", "sql", "machine learning", "tableau"], "experience_min": 3.0, "experience_max": 6.0, "salary_min": 120000, "salary_max": 165000, "job_type": "full-time", "remote": False, "category": "Data Science"},
    {"title": "DevOps Engineer", "company": "CloudFirst Technologies", "location": "Denver, CO", "description": "DevOps Engineer to manage cloud infrastructure. Requirements: 4+ years DevOps/SRE, AWS or Azure, Docker, Kubernetes, Terraform, CI/CD (Jenkins, GitHub Actions), Linux, monitoring (Prometheus, Grafana), Python scripting.", "skills_required": ["aws", "docker", "kubernetes", "terraform", "ci/cd", "linux", "python", "jenkins", "git"], "experience_min": 4.0, "experience_max": 7.0, "salary_min": 130000, "salary_max": 175000, "job_type": "full-time", "remote": True, "category": "DevOps"},
    {"title": "Junior Software Engineer", "company": "GrowthTech", "location": "Boston, MA", "description": "Great opportunity for Junior Software Engineer. Requirements: Bachelor's in CS, Python or Java, data structures, databases (SQL), Git, strong learning ability.", "skills_required": ["python", "java", "sql", "git", "html", "css", "javascript"], "experience_min": 0.0, "experience_max": 2.0, "salary_min": 70000, "salary_max": 95000, "job_type": "full-time", "remote": False, "category": "Software Engineering"},
    {"title": "Cloud Solutions Architect", "company": "Enterprise Cloud Co.", "location": "Remote", "description": "Cloud Solutions Architect for enterprise solutions. Requirements: 7+ years software engineering, 4+ years cloud architecture, AWS/Azure certification, microservices, security best practices, serverless.", "skills_required": ["aws", "azure", "microservices", "docker", "kubernetes", "terraform", "python", "java", "sql"], "experience_min": 7.0, "experience_max": 12.0, "salary_min": 170000, "salary_max": 230000, "job_type": "full-time", "remote": True, "category": "Cloud Architecture"},
    {"title": "Mobile App Developer (React Native)", "company": "AppWorks Inc.", "location": "Los Angeles, CA", "description": "Build cross-platform mobile apps with React Native. Requirements: 3+ years mobile dev, React Native, TypeScript, iOS/Android knowledge, RESTful APIs, app store deployment.", "skills_required": ["react", "typescript", "javascript", "css", "git", "rest api", "node.js"], "experience_min": 3.0, "experience_max": 5.0, "salary_min": 115000, "salary_max": 155000, "job_type": "full-time", "remote": False, "category": "Mobile Development"},
    {"title": "Backend Engineer (Java/Spring Boot)", "company": "FinTech Solutions", "location": "Charlotte, NC", "description": "Backend Engineer for fintech. Requirements: 4+ years Java, Spring Boot, microservices, PostgreSQL, Redis, message queues, Docker.", "skills_required": ["java", "spring boot", "postgresql", "redis", "docker", "microservices", "rest api", "sql", "git"], "experience_min": 4.0, "experience_max": 7.0, "salary_min": 130000, "salary_max": 170000, "job_type": "full-time", "remote": False, "category": "Backend Development"},
    {"title": "NLP Research Engineer", "company": "LangTech AI", "location": "Remote", "description": "Work on cutting-edge NLP systems. Requirements: MS/PhD in CS or NLP, 3+ years NLP experience, Python, transformers, language models, spaCy, HuggingFace, large-scale data processing.", "skills_required": ["python", "nlp", "machine learning", "deep learning", "tensorflow", "pytorch", "pandas", "numpy"], "experience_min": 3.0, "experience_max": 6.0, "salary_min": 145000, "salary_max": 195000, "job_type": "full-time", "remote": True, "category": "Machine Learning"},
    {"title": "UI/UX Designer & Developer", "company": "DesignFirst Agency", "location": "Portland, OR", "description": "Combine design and development. Requirements: 3+ years UI/UX, Figma, HTML, CSS, JavaScript, React or Vue, accessibility standards, design systems.", "skills_required": ["html", "css", "javascript", "react", "figma", "tailwind", "git"], "experience_min": 3.0, "experience_max": 5.0, "salary_min": 95000, "salary_max": 135000, "job_type": "full-time", "remote": True, "category": "Design"},
    {"title": "Database Administrator", "company": "DataVault Systems", "location": "Dallas, TX", "description": "Manage and optimize database infrastructure. Requirements: 5+ years DBA, PostgreSQL, MySQL, MongoDB, query optimization, backup/recovery, cloud databases (RDS), Python scripting.", "skills_required": ["postgresql", "mysql", "mongodb", "sql", "python", "linux", "aws", "redis"], "experience_min": 5.0, "experience_max": 8.0, "salary_min": 120000, "salary_max": 160000, "job_type": "full-time", "remote": False, "category": "Database"},
    {"title": "Cybersecurity Analyst", "company": "SecureNet Corp.", "location": "Washington, DC", "description": "Protect systems as Cybersecurity Analyst. Requirements: 3+ years cybersecurity, network security, SIEM tools, penetration testing, compliance (SOC2, ISO 27001), Python scripting.", "skills_required": ["python", "linux", "sql", "git", "communication"], "experience_min": 3.0, "experience_max": 6.0, "salary_min": 100000, "salary_max": 140000, "job_type": "full-time", "remote": False, "category": "Cybersecurity"},
    {"title": "Product Manager - AI/ML", "company": "InnovateTech", "location": "San Jose, CA", "description": "Lead AI/ML product initiatives. Requirements: 5+ years product management, technical background, ML/AI understanding, agile, analytical mindset, communication and leadership.", "skills_required": ["agile", "scrum", "python", "sql", "machine learning", "communication", "leadership"], "experience_min": 5.0, "experience_max": 9.0, "salary_min": 150000, "salary_max": 200000, "job_type": "full-time", "remote": False, "category": "Product Management"},
]


def seed_database():
    create_tables()
    db = SessionLocal()
    try:
        if db.query(Job).count() > 0:
            print("Database already seeded. Skipping.")
            return
        for job_data in SAMPLE_JOBS:
            job = Job(title=job_data["title"], company=job_data["company"], location=job_data["location"], description=job_data["description"], skills_required=job_data["skills_required"], experience_min=job_data["experience_min"], experience_max=job_data["experience_max"], salary_min=job_data.get("salary_min"), salary_max=job_data.get("salary_max"), job_type=job_data["job_type"], remote=job_data["remote"], category=job_data.get("category"), posted_date=datetime.utcnow() - timedelta(days=random.randint(1, 30)), is_active=True)
            db.add(job)
        db.commit()
        print(f"Seeded {len(SAMPLE_JOBS)} job listings!")
    except Exception as e:
        db.rollback()
        print(f"Error: {e}")
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
