export interface ResumeSummary { id: number; filename: string; skills_count: number; experience_years: number; ats_score: number; created_at: string; }
export interface Education { text: string; type: string; year?: number; }
export interface Job { id: number; title: string; company: string; location: string | null; description: string; skills_required: string[] | null; experience_min: number; experience_max: number; salary_min: number | null; salary_max: number | null; job_type: string | null; remote: boolean; category: string | null; posted_date: string; is_active: boolean; }
export interface SkillGap { skill: string; priority: string; difficulty: string; recommended_course: { platform: string; course: string; duration: string; }; }
export interface Recommendation { id: number; resume_id: number; job_id: number; match_score: number; skill_match_score: number; experience_match_score: number; semantic_similarity_score: number; matched_skills: string[]; missing_skills: string[]; skill_gaps: SkillGap[]; suggested_certifications: string[]; career_suggestions: string | null; recruiter_summary: string | null; created_at: string; job: Job | null; }
export interface ATSScore { overall_score: number; format_score: number; keyword_score: number; readability_score: number; completeness_score: number; suggestions: string[]; }
export interface AnalyticsOverview { total_resumes: number; total_jobs: number; total_recommendations: number; avg_match_score: number; top_skills_in_demand: { skill: string; count: number }[]; skill_gap_summary: { skill: string; count: number }[]; match_score_distribution: { range: string; count: number }[]; }
export interface ResumeAnalytics { resume_id: number; total_recommendations: number; avg_match_score: number; top_match_score: number; ats_score: number; skills_count: number; experience_years: number; skills_matched_across_jobs: string[]; skills_commonly_missing: string[]; match_score_distribution: { range: string; count: number }[]; top_matching_jobs: { job_id: number; match_score: number; matched_skills: string[] }[]; }
export interface CareerSuggestions { current_role_fit: string; role_fit_score: number; suggested_roles: { role: string; fit_percentage: number }[]; growth_stage: string; growth_paths: { stage: string; timeline: string }[]; industry_trends: string[]; salary_insights: Record<string, string>; }
export interface SkillGapAnalysis { current_skills: string[]; in_demand_skills: string[]; missing_skills: string[]; skill_match_percentage: number; skill_gaps: SkillGap[]; suggested_certifications: string[]; }
